#!/usr/bin/env bash
# vim: set ft=sh:

ARGS="$@"

SCRIPT_DIR="$( cd "$(dirname "$0")" ; pwd -P )"
cd "$SCRIPT_DIR/.."

if [ -z "$ARGS" ] ; then
  ./node_modules/.bin/eslint --fix --color '**/**/*.js'
else
  ./node_modules/.bin/eslint --fix --color --config --ignore '**/**/*.js' $ARGS
fi
