#!/usr/bin/env node
// vim: set ft=javascript:

// This script is the equivalent of `stylelint`, except
// the output is in JUnit format, and it is sent to stdout.

const fs = require('fs');
const stylelint = require('stylelint');
const junitFormatter = require('stylelint-junit-formatter');

const stylelintOptions = {
  files: '**/*.scss',
  formatter: junitFormatter,
};

stylelint.lint(stylelintOptions)
  .then((resultObject) => {
    console.log(resultObject.output);
    // Exit with code 1 if errors or warnings were found.
    if (resultObject.output.match(/errors="?[1-9]/) || resultObject.output.match(/warnings="?[1-9]/)) {
      process.exit(1);
    }
  });
