#!/usr/bin/env bash
# vim: set ft=sh:

SCRIPT_DIR="$( cd "$(dirname "$0")" ; pwd -P )"
cd "$SCRIPT_DIR/.."
ARGS="$@"
if [ -z "$ARGS" ] ; then
  ./node_modules/.bin/stylelint --color --fix '**/**/*.scss'
else
  ./node_modules/.bin/stylelint --color --fix $ARGS
fi
